# Generated by Django 4.2.5 on 2024-04-04 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user_info',
        ),
    ]
