# Generated by Django 4.2.5 on 2024-04-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_cart_user_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_item_price',
            field=models.IntegerField(default=0),
        ),
    ]
