# Generated by Django 4.2.5 on 2024-04-01 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_total_price', models.IntegerField()),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.cart')),
            ],
        ),
    ]
