# Generated by Django 4.2.5 on 2024-04-06 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_cart_cart_item_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cart_item_price',
            new_name='cart_item_total_price',
        ),
    ]
