# Generated by Django 4.2.5 on 2024-04-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_quantity',
            field=models.IntegerField(),
        ),
    ]
