# Generated by Django 4.2.5 on 2024-04-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_alter_item_item_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(default='Null', upload_to='./products/img'),
        ),
    ]
