# Generated by Django 4.2.5 on 2024-04-09 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_item_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_invoice',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
