# Generated by Django 4.2.5 on 2024-04-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_alter_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(default='Null', upload_to='./main/static/img/products'),
        ),
    ]
