# Generated by Django 4.2.5 on 2024-04-10 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_transaction_transaction_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_order_status',
            field=models.CharField(default='Processing', max_length=200),
            preserve_default=False,
        ),
    ]
