# Generated by Django 4.2.5 on 2024-04-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0011_remove_item_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
